# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'currencyConvert.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TipoDeCambio(object):
    def setupUi(self, TipoDeCambio):
        TipoDeCambio.setObjectName("TipoDeCambio")
        TipoDeCambio.resize(517, 236)
        self.centralwidget = QtWidgets.QWidget(TipoDeCambio)
        self.centralwidget.setObjectName("centralwidget")
        self.lblConvertir = QtWidgets.QLabel(self.centralwidget)
        self.lblConvertir.setGeometry(QtCore.QRect(20, 20, 47, 13))
        self.lblConvertir.setObjectName("lblConvertir")
        self.leImporte = QtWidgets.QLineEdit(self.centralwidget)
        self.leImporte.setGeometry(QtCore.QRect(80, 20, 113, 20))
        self.leImporte.setObjectName("leImporte")
        self.gbDe = QtWidgets.QGroupBox(self.centralwidget)
        self.gbDe.setGeometry(QtCore.QRect(20, 80, 151, 111))
        self.gbDe.setObjectName("gbDe")
        self.rbDeUS = QtWidgets.QRadioButton(self.gbDe)
        self.rbDeUS.setGeometry(QtCore.QRect(10, 30, 82, 17))
        self.rbDeUS.setChecked(True)
        self.rbDeUS.setObjectName("rbDeUS")
        self.rbDeUK = QtWidgets.QRadioButton(self.gbDe)
        self.rbDeUK.setGeometry(QtCore.QRect(10, 60, 82, 17))
        self.rbDeUK.setObjectName("rbDeUK")
        self.rbDeAUS = QtWidgets.QRadioButton(self.gbDe)
        self.rbDeAUS.setGeometry(QtCore.QRect(10, 90, 82, 17))
        self.rbDeAUS.setObjectName("rbDeAUS")
        self.gbA = QtWidgets.QGroupBox(self.centralwidget)
        self.gbA.setGeometry(QtCore.QRect(210, 80, 151, 111))
        self.gbA.setObjectName("gbA")
        self.rbAUS = QtWidgets.QRadioButton(self.gbA)
        self.rbAUS.setGeometry(QtCore.QRect(20, 20, 82, 17))
        self.rbAUS.setChecked(True)
        self.rbAUS.setObjectName("rbAUS")
        self.rbAUK = QtWidgets.QRadioButton(self.gbA)
        self.rbAUK.setGeometry(QtCore.QRect(20, 50, 82, 17))
        self.rbAUK.setObjectName("rbAUK")
        self.rbAAUS = QtWidgets.QRadioButton(self.gbA)
        self.rbAAUS.setGeometry(QtCore.QRect(20, 80, 82, 17))
        self.rbAAUS.setObjectName("rbAAUS")
        self.lblResultado = QtWidgets.QLabel(self.centralwidget)
        self.lblResultado.setGeometry(QtCore.QRect(370, 110, 47, 13))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.lblResultado.setFont(font)
        self.lblResultado.setObjectName("lblResultado")
        self.lblCambio = QtWidgets.QLabel(self.centralwidget)
        self.lblCambio.setGeometry(QtCore.QRect(370, 140, 47, 13))
        self.lblCambio.setObjectName("lblCambio")
        self.pbTipoCambio = QtWidgets.QPushButton(self.centralwidget)
        self.pbTipoCambio.setGeometry(QtCore.QRect(410, 170, 75, 23))
        self.pbTipoCambio.setObjectName("pbTipoCambio")
        TipoDeCambio.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TipoDeCambio)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 517, 21))
        self.menubar.setObjectName("menubar")
        TipoDeCambio.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TipoDeCambio)
        self.statusbar.setObjectName("statusbar")
        TipoDeCambio.setStatusBar(self.statusbar)

        self.retranslateUi(TipoDeCambio)
        QtCore.QMetaObject.connectSlotsByName(TipoDeCambio)

    def retranslateUi(self, TipoDeCambio):
        _translate = QtCore.QCoreApplication.translate
        TipoDeCambio.setWindowTitle(_translate("TipoDeCambio", "Tipo de cambio"))
        self.lblConvertir.setText(_translate("TipoDeCambio", "Convertir"))
        self.gbDe.setTitle(_translate("TipoDeCambio", "De:"))
        self.rbDeUS.setText(_translate("TipoDeCambio", "US$"))
        self.rbDeUK.setText(_translate("TipoDeCambio", "UK£"))
        self.rbDeAUS.setText(_translate("TipoDeCambio", "AUS$"))
        self.gbA.setTitle(_translate("TipoDeCambio", "A:"))
        self.rbAUS.setText(_translate("TipoDeCambio", "US$"))
        self.rbAUK.setText(_translate("TipoDeCambio", "UK£"))
        self.rbAAUS.setText(_translate("TipoDeCambio", "AUS$"))
        self.lblResultado.setText(_translate("TipoDeCambio", "Resultado"))
        self.lblCambio.setText(_translate("TipoDeCambio", "0"))
        self.pbTipoCambio.setText(_translate("TipoDeCambio", "Convertir"))
